export default function Head() {
  return (
    <>
      <title>Reserve at Milestones Grill (Toronto) | OpenTable</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
// SELECT * FROM restaurant WHERE id = 4
// prisma.restuant.findUnique(4)
// 1SGUSUT5FT7ZdHRb
